---
- name: Login to IaaS
  ovirt_auth:
    url: https://iaas.ull.es/ovirt-engine/api
    insecure: yes
    # username: "{{ ovirt_username }}"
    # password: "{{ ovirt_password }}"
    username: alu0100887037@ULL
    password: xd
    headers:
      filter: true
  debugger: never
