---
# tasks file for vm_create
- name: Create a VM
  ovirt_vm:
    auth: "{{ ovirt_auth }}"
    cluster: "{{ item.cluster }}"
    name: "{{ item.name }}"
    cpu_cores: 1
    cpu_sockets: 1
    memory: 1GiB
    template: "{{ item.distro }}"
    nics: "{{ node_nics }}"
    state: absent
    wait: yes
  with_items: "{{ nodes }}"
