---
- name: Crear MVs.
  hosts: localhost
  gather_facts: false

  # Variables
  vars_files:
    - ../files/pabloTFG.yaml

  vars:
    ssh_keys: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDOg/NpAdkuEs5SO6J3CXyP8cwrKfzt8BGURkbDjLf+64/Q2iJ+fejwNktTTUzLgFXeNgT2obetqR/J/OTctyhM3N6/3K4Td9PKk9FHEY5/w5kTr2s9PDjRRlyyRcy0riahEzxYuMzDfJIWPFYFs1Wopu0u82W5B0JCF3+Jj0shjAsT7sFQz3da82OyHurVj0djHhkTN1ksea3jUU+n4LRzFfa+OOBjgPcL9L4SGAzOI3OWC2wB3qOZ0ZpaITM1N4QAhE7pbsXxJy+MBrtEgyV8LQLTw1T/pj6m/uwh8xSpYTcUKiPIzsnV1nmHLt/Gl5HipKFurT0N7mdYZzQ3ORKJ usuario@debian

  # Pre-tasks
  pre_tasks:
    - name: Login to IaaS
      include_role:
        name: iaas_login

  # Tasks
  roles:
    - vm_remove

  # Post-tasks
  post_tasks:
    - name: Logout from IaaS
      include_role:
        name: iaas_logout