---
- name: Reset user's password
  hosts: "{{ inventoryGroup }}"
  remote_user: "{{ targetUsername }}"
  gather_facts: false

  # Variables
  vars_files:
    - ../files/pabloTFG.yaml
    - ../files/credentials.yaml

  vars:
    nodes: [ "{{ vmName }}" ]
    cluster: Cluster-Rojo

  # Pre-tasks
  pre_tasks:
    - name: Login to IaaS
      include_role:
        name: iaas_login

  # Tasks
  # roles:
  tasks:
    - name: Reset password
      script: ./scripts/reset_password.sh "{{ targetUsername }}"

  # Post-tasks
  post_tasks:
    - name: Logout from IaaS
      include_role:
        name: iaas_logout
