---
- name: Reset user's password
  hosts: all
  remote_user: ansible
  gather_facts: true

  # Variables
  vars_files:
    - ../files/pabloTFG.yaml
    - ../files/credentials.yaml

  # Pre-tasks
  pre_tasks:
    - name: Debug
      debug:
        var: ansible_facts
    - name: Login to IaaS
      include_role:
        name: iaas_login

  # Tasks
  # roles:
  tasks:
  #    - name: Copy script
  #      copy:
  #        src: ./scripts/reset_password.sh
  #        dest: /tmp

  # Post-tasks
  post_tasks:
    - name: Logout from IaaS
      include_role:
        name: iaas_logout
