---
- name: Create VMs.
  hosts: localhost
  gather_facts: false

  # Variables
  vars_files:
    - ../files/pabloTFG.yaml
    - ../files/credentials.yaml

  vars:
    node_nics:
      - name: nic1
        profile_name: DOCP2P-4010

  # Pre-tasks
  pre_tasks:
    - name: Login to IaaS
      include_role:
        name: iaas_login

  # Tasks
  roles:
    - vm_remove
    - vm_create
    - vm_init

  # Post-tasks
  post_tasks:
    - name: Logout from IaaS
      include_role:
        name: iaas_logout
