---
- name: Reset user's password
  hosts: "{{ vmName }}"
  remote_user: "{{ targetUsername }}"
  gather_facts: false

  # Variables
  vars_files:
    - ../files/pabloTFG.yaml
    - ../files/credentials.yaml

  # Pre-tasks
  pre_tasks:
    - name: Login to IaaS
      include_role:
        name: iaas_login

  # Tasks
  # roles:
  tasks:
    - name: Copy script
      copy:
        src: ./scripts/reset_password.sh
        dest: /tmp

  # Post-tasks
  post_tasks:
    - name: Logout from IaaS
      include_role:
        name: iaas_logout
